# Python script to generate namelist.wps
import defaultNamelistVars as nameVars

# w means write, + means create file if it doesn't exist
#for i in range(10):
#f.write("this is line %d\r\n" % (i+1)) # \r is carriage return, \n is newline. both are required for new line in network virtual terminal session
# f.open("FILENAME", "a+") a means append
#f.write('%s %s' % ('one', 'two'))

def main():
	### Receive start and end dates
	sd_y = input("start_date: year? ")
	sd_m = input("\tmonth? ")
	sd_d = input("\tday? ")
	sd_h = input("\thour? ")
	sd_min = input("\tminute? ")
	sd_s = input("\tsecond? ")
	start_date = nameVars.start_date(sd_y,sd_m,sd_d,sd_h,sd_min,sd_s)
	ed_y = input("end_date: year? ")
	ed_m = input("\tmonth? ")
	ed_d = input("\tday? ")
	ed_h = input("\thour? ")
	ed_min = input("\tminute? ")
	ed_s = input("\tsecond? ")
	end_date = nameVars.end_date(ed_y,ed_m,ed_d,ed_h,ed_min,ed_s)
	
	run_duration = end_date - start_date
	r_days = run_duration.days
	r_hours = run_duration.seconds//3600
	r_minutes = (run_duration.seconds%3600)//60
	r_seconds = (run_duration.seconds%3600)%60
	print('run_days: ',r_days)
	print('run_hours: ',r_hours)
	print('run_minutes: ',r_minutes)
	print('run_seconds: ',r_seconds)
	
	############################ WPS #######################################
	f = open("namelist.wps","w+") 
	f.write("&share\r\n")
	f.write(" wrf_core = %s,\r\n" % (nameVars.wrf_core))
	f.write(" max_dom = %s,\r\n" % (nameVars.max_dom))
	f.write(" start_date = %s,\r\n" % (start_date.strftime('%Y-%m-%d_%H:%M:%S')))
	f.write(" end_date = %s,\r\n" % (end_date.strftime('%Y-%m-%d_%H:%M:%S')))
	f.write(" interval_seconds = %s,\r\n" % (nameVars.interval_seconds(r_days,r_hours,r_minutes,r_seconds)))
	f.write(" io_form_geogrid = %s,\r\n" % (nameVars.io_form_geogrid))
	f.write("\\\r\n\r\n")
	
	f.write("&geogrid\r\n")
	f.write(" parent_id = %s,\r\n" % (nameVars.parent_id))
	f.write(" parent_grid_ratio = %s,\r\n" % (nameVars.parent_grid_ratio))
	f.write(" i_parent_start = %s,\r\n" % (nameVars.i_parent_start))
	f.write(" j_parent_start = %s,\r\n" % (nameVars.j_parent_start))
	f.write(" e_we = %s,\r\n" % (nameVars.e_we))
	f.write(" e_sn = %s,\r\n" % (nameVars.e_sn))
	f.write(" geog_data_res = %s,\r\n" % (nameVars.geog_data_res))
	f.write(" dx = %s,\r\n" % (nameVars.dx))
	f.write(" dy = %s,\r\n" % (nameVars.dy))
	f.write(" map_proj = %s,\r\n" % (nameVars.map_proj))
	f.write(" ref_lat = %s,\r\n" % (nameVars.ref_lat))
	f.write(" ref_long = %s,\r\n" % (nameVars.ref_long))
	f.write(" truelat1 = %s,\r\n" % (nameVars.truelat1))
	f.write(" truelat2 = %s,\r\n" % (nameVars.truelat2))
	f.write(" stand_lon = %s,\r\n" % (nameVars.stand_lon))
	f.write(" geog_data_path = %s,\r\n" % (nameVars.geog_data_path))
	f.write("\\\r\n\r\n")
	
	f.write("&ungrib\r\n")
	f.write(" out_format = %s,\r\n" % (nameVars.out_format))
	f.write(" prefix = %s,\r\n" % (nameVars.prefix))
	f.write("\\\r\n\r\n")
	
	f.write("&metgrid\r\n")
	f.write(" fg_name = %s,\r\n" % (nameVars.fg_name))
	f.write(" io_form_metgrid = %s,\r\n" % (nameVars.io_form_metgrid))
	f.write("\\\r\n\r\n")
	
	f.close()


	############################ INPUT #######################################
	i = open("namelist.input","w+")
	i.write("&time_control\r\n")
	i.write(" run_days = %s,\r\n" % (r_days))
	i.write(" run_hours = %s,\r\n" % (r_hours))
	i.write(" run_minutes = %s,\r\n" % (r_minutes))
	i.write(" run_days = %s,\r\n" % (r_seconds))
	i.write(" start_year = %s,\r\n" % (nameVars.start_year(start_date.strftime('%Y')
)))
	i.write(" start_month = %s,\r\n" % (nameVars.start_month(start_date.strftime('%m')
)))
	i.write(" start_day = %s,\r\n" % (nameVars.start_day(start_date.strftime('%d')
)))
	i.write(" start_hour = %s,\r\n" % (nameVars.start_hour(start_date.strftime('%H')
)))
	i.write(" start_minute = %s,\r\n" % (nameVars.start_minute(start_date.strftime('%M')
)))
	i.write(" start_second = %s,\r\n" % (nameVars.start_second(start_date.strftime('%S')
)))
	i.write(" end_year = %s,\r\n" % (nameVars.end_year(end_date.strftime('%Y')
)))
	i.write(" end_month = %s,\r\n" % (nameVars.end_month(end_date.strftime('%m'))))
	i.write(" end_day = %s,\r\n" % (nameVars.end_day(end_date.strftime('%d'))))
	i.write(" end_hour = %s,\r\n" % (nameVars.end_hour(end_date.strftime('%H'))))
	i.write(" end_minute = %s,\r\n" % (nameVars.end_minute(end_date.strftime('%M'))))
	i.write(" end_second = %s,\r\n" % (nameVars.end_second(end_date.strftime('%S'))))
	
	i.write(" interval_seconds = %s\r\n" % (nameVars.interval_seconds(r_days,r_hours,r_minutes,r_seconds)))
	i.write(" input_from_file = %s\r\n" % (nameVars.input_from_file))
	i.write(" history_interval = %s\r\n" % (nameVars.history_interval))
	i.write(" frames_per_outfile = %s\r\n" % (nameVars.frames_per_outfile))
	i.write(" restart = %s\r\n" % (nameVars.restart))
	i.write(" restart_interval = %s\r\n" % (nameVars.restart_interval))
	i.write(" io_form_history = %s\r\n" % (nameVars.io_form_history))
	i.write(" io_form_restart = %s\r\n" % (nameVars.io_form_restart))
	i.write(" io_form_input = %s\r\n" % (nameVars.io_form_input))
	i.write(" io_form_boundary = %s\r\n" % (nameVars.io_form_boundary))
	i.write(" debug_level = %s\r\n" % (nameVars.debug_level))
	i.write("\\\r\n\r\n")
	
	i.write("&domains\r\n")
	i.write(" time_step = %s\r\n" % (nameVars.time_step))
	i.write(" time_step_fract_num = %s\r\n" % (nameVars.time_step_fract_num))
	i.write(" time_step_fract_den = %s\r\n" % (nameVars.time_step_fract_den))
	i.write(" max_dom = %s\r\n" % (nameVars.max_dom))
	i.write(" e_we = %s\r\n" % (nameVars.e_we))
	i.write(" e_sn = %s\r\n" % (nameVars.e_sn))
	i.write(" e_vert = %s\r\n" % (nameVars.e_vert))
	i.write(" p_top_requested = %s\r\n" % (nameVars.p_top_requested))
	i.write(" num_metgrid_levels = %s\r\n" % (nameVars.num_metgrid_levels))
	i.write(" num_metgrid_soil_levels = %s\r\n" % (nameVars.num_metgrid_soil_levels))
	i.write(" dx = %s\r\n" % (nameVars.dx))
	i.write(" dy = %s\r\n" % (nameVars.dy))
	i.write(" grid_id = %s\r\n" % (nameVars.grid_id))
	i.write(" parent_id = %s\r\n" % (nameVars.parent_id))
	i.write(" i_parent_start = %s\r\n" % (nameVars.i_parent_start))
	i.write(" j_parent_start = %s\r\n" % (nameVars.j_parent_start))
	i.write(" parent_grid_ratio = %s\r\n" % (nameVars.parent_grid_ratio))
	i.write(" feedback = %s\r\n" % (nameVars.feedback))
	i.write(" smooth_option = %s\r\n" % (nameVars.smooth_option))
	i.write("\\\r\n\r\n")
	
	i.write("&physics\r\n")
	i.write(" mp_physics = %s\r\n" % (nameVars.mp_physics))
	i.write(" ra_lw_physics = %s\r\n" % (nameVars.ra_lw_physics))
	i.write(" ra_sw_physics = %s\r\n" % (nameVars.ra_sw_physics))
	i.write(" radt = %s\r\n" % (nameVars.radt))
	i.write(" sf_sfclay_physics = %s\r\n" % (nameVars.sf_sfclay_physics))
	i.write(" sf_surface_physics = %s\r\n" % (nameVars.sf_surface_physics))
	i.write(" bl_pbl_physics = %s\r\n" % (nameVars.bl_pbl_physics))
	i.write(" bldt = %s\r\n" % (nameVars.bldt))
	i.write(" cu_physics = %s\r\n" % (nameVars.cu_physics))
	i.write(" cudt = %s\r\n" % (nameVars.cudt))
	i.write(" isfflx = %s\r\n" % (nameVars.isfflx))
	i.write(" ifsnow = %s\r\n" % (nameVars.ifsnow))
	i.write(" icloud = %s\r\n" % (nameVars.icloud))
	i.write(" surface_input_source = %s\r\n" % (nameVars.surface_input_source))
	i.write(" num_soil_layers = %s\r\n" % (nameVars.num_soil_layers))
	i.write(" num_land_cat = %s\r\n" % (nameVars.num_land_cat))
	i.write(" sf_urban_physics = %s\r\n" % (nameVars.sf_urban_physics))
	i.write("\\\r\n\r\n")
	
	i.write("&fdda\r\n")
	i.write("\\\r\n\r\n")
	
	i.write("&dynamics\r\n")
	i.write(" w_damping = %s\r\n" % (nameVars.w_damping))
	i.write(" diff_opt = %s\r\n" % (nameVars.diff_opt))
	i.write(" km_opt = %s\r\n" % (nameVars.km_opt))
	i.write(" diff_6th_opt = %s\r\n" % (nameVars.diff_6th_opt))
	i.write(" diff_6th_factor = %s\r\n" % (nameVars.diff_6th_factor))
	i.write(" base_temp = %s\r\n" % (nameVars.base_temp))
	i.write(" damp_opt = %s\r\n" % (nameVars.damp_opt))
	i.write(" zdamp = %s\r\n" % (nameVars.zdamp))
	i.write(" dampcoef = %s\r\n" % (nameVars.dampcoef))
	i.write(" khdif = %s\r\n" % (nameVars.khdif))
	i.write(" kvdif = %s\r\n" % (nameVars.kvdif))
	i.write(" non_hydrostatic = %s\r\n" % (nameVars.non_hydrostatic))
	i.write(" moist_adv_opt = %s\r\n" % (nameVars.moist_adv_opt))
	i.write(" scalar_adv_opt = %s\r\n" % (nameVars.scalar_adv_opt))
	i.write("\\\r\n\r\n")
	
	i.write("&bdy_control\r\n")
	i.write(" spec_bdy_width = %s\r\n" % (nameVars.spec_bdy_width))
	i.write(" spec_zone = %s\r\n" % (nameVars.spec_zone))
	i.write(" relax_zone = %s\r\n" % (nameVars.relax_zone))
	i.write(" specified = %s\r\n" % (nameVars.specified))
	i.write(" nested = %s\r\n" % (nameVars.nested))
	i.write("\\\r\n\r\n")
	
	i.write("&grib2\r\n")
	i.write("\\\r\n\r\n")
	
	i.write("&namelist_quilt\r\n")
	i.write(" nio_tasks_per_group = %s\r\n" % (nameVars.nio_tasks_per_group))
	i.write(" nio_groups = %s\r\n" % (nameVars.nio_groups))
	i.write("\\\r\n\r\n")
	
	i.close()

main()



